# DEVELOPMENT DOCKER-COMPOSE FILE

version: '3.9'
services:
  space-db:
    image: postgres:14-alpine
    restart: unless-stopped
    hostname: space.db
    container_name: space-db
    volumes:
      - .data/space_db/postgresql:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: space-db
      POSTGRES_PASSWORD: space-db
      POSTGRES_DB: space-db
    networks:
      - backend-net

  # [CERTIFICATION API] #################################################
  space.files:
    image: httpd:latest
    container_name: space.files
    hostname: space.files
    ports:
      - '9990:80'
    volumes:
      - ./.fileserver:/usr/local/apache2/htdocs
    networks:
      - backend-net
  
  cert:
    hostname: cert
    image: tum-ai-space-tools-certification-server
    build: ./tools/certification-api
    restart: unless-stopped
    container_name: cert
    command: npm run dev
    ports:
      - '3009:80'
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
    name: backend-net
