version: '3.8'

services:
  space:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/space
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/spacedb
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: spacedb
    environment:
      POSTGRES_DB: spacedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - app-network

networks:
  app-network: