---
#-------------------------------------------------------------------------------#
APPLICATION:
    APP_NAME: 'TUM.ai Space'
    API_FRAMEWORK_NAME: 'fastapi'

    # set "wsgi" if running via gunicorn, "asgi" for uvicorn
    FASTAPI_RUNNING_PROTOCOL: 'wsgi'
#-------------------------------------------------------------------------------#
AUTH:
    AUTH_API_BASE_PATH: '/auth'
    API_DOMAIN: 'http://api.tum-ai-dev.com:15950'
    AUTH_WEBSITE_BASE_PATH: '/auth'
    AUTH_WEBSITE_DOMAIN: 'http://auth.tum-ai-dev.com:15950'
    AUTH_ALLOWED_ORIGINS:
        # Should contain AUTH_WEBSITE_DOMAIN
        - 'http://space.tum-ai.com'
        - 'http://space.staging.tum-ai.com'
        - 'http://localhost'
        - 'http://localhost:3000'
        - 'http://192.168.178.21'
        - 'http://192.168.178.21:3000'
    USERS_DASHBOARD_API_KEY: 'someApiKey'
#-------------------------------------------------------------------------------#
LOGGER:
    LOGGER_NAME: 'tumai-space-global'
    LOG_LEVEL: 'DEBUG'
#-------------------------------------------------------------------------------#
