# ENV VARIABLES NEEDED FOR BUILD
# - ENVIRON=development|staging|prod
# - FIREBASE_ADMINSDK_CERTIFICATE
# ENV VARIABLES NEEDED FOR RUN
# - API_PORT
# [database environment]
# - DB_HOST=space.db(.staging|.prod)
# - DB_PORT
# - DB_NAME
# - DB_USER
# - DB_PASSWORD
# [mail environment]
# - MAIL_USERNAME
# - MAIL_PASSWORD
# - MAIL_FROM
# - MAIL_PORT
# - MAIL_SERVER
# - MAIL_FROM_NAME

version: '3.9'
services:
  api:
    container_name: "tum-ai-space-api-${ENVIRON}"
    image: "tum-ai-space-api-${ENVIRON}"
    build: .
    restart: unless-stopped
    command: gunicorn space_api.main:app -k uvicorn.workers.UvicornWorker --workers=4 --reload --bind=0.0.0.0
    # ports:
    #   - '${API_PORT}:8000'
    networks:
      - backend-net
      - proxy-net
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - environment=${ENVIRON}
      - FIREBASE_ADMINSDK_CERTIFICATE=${FIREBASE_ADMINSDK_CERTIFICATE}
      # database environment
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # mail environment
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
    volumes:
      - .secrets/:/apps/space/api/.secrets/

networks:
  backend-net:
    driver: bridge
    name: backend-net
  proxy-net:
    driver: bridge
    name: proxy-net
