name: space
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pip
    - setuptools-scm
    - setuptools

    # development
    - ipykernel

    # linting
    - mypy
    - yapf
    - ruff
    - typing_extensions
    - types-python-dateutil
    - types-pyyaml

    # testing
    - pytest
    - pytest-cov

    # runtime
    - fastapi
    - gunicorn
    - httptools
    - httpx
    - psycopg2-binary
    - pydantic >=2.0
    - python-dateutil
    - pyyaml
    - starlette
    - sqlalchemy >=2.0
    - sqlalchemy-utils
    - uvicorn
    - uvloop
    - pre_commit

    # database migrations
    - alembic

    - pip:
          # linting
          - types-pyyaml
          - types-python-dateutil
          - types-requests

          # runtime
          - fastapi-mail
          - firebase-admin
