name: Backend CI - /api

on:
  pull_request:
    paths:
    - 'api/**'
    branches:
      - main
    
  workflow_dispatch:

jobs:
  ci-build:
    name: Ubuntu CI for backend /api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@5b9dc5cf9560f2808ade896803b2f68cfcfdd52b
        with:
          environment-file: api/environment.yml
          init-shell: bash
      - name: Lint with Ruff
        run: cd ./api && python -m ruff check .

      # TODO: integrate mypy
      
      - name: write secret file
        run: |
          mkdir -p /home/runner/work/space/space/api/.secrets        
          touch /home/runner/work/space/space/api/.secrets/tumai-space-firebase-adminsdk.json 
          echo "${{ secrets.FIREBASE_ADMINSDK_CERTIFICATE_STAGING }}" > /home/runner/work/space/space/api/.secrets/tumai-space-firebase-adminsdk.json
      # TODO: shorten paths

      - name: Run pytest
        run: python -m pytest .
        working-directory: /home/runner/work/space/space/api

      # - name: Build docker container
      #   run: 
