name: Build & deploy backend to tumai rootserver

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  ENVIRON: prod
  FIREBASE_ADMINSDK_CERTIFICATE: ${{ secrets.FIREBASE_ADMINSDK_CERTIFICATE }}
  API_PORT: 8000
  # [database environment]
  DB_HOST: space.db.staging
  DB_PORT: 5432
  DB_NAME: space-db
  DB_USER: space-db
  DB_PASSWORD: ${{ secrets.SPACE_DB_PASSWORD }}
  # [mail environment]
  MAIL_USERNAME: space@tum-ai.com
  MAIL_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
  MAIL_FROM: space@tum-ai.com
  MAIL_PORT: 587
  MAIL_SERVER: smtp.gmail.com
  MAIL_FROM_NAME: TUM.ai Space Team
  # [deployment server]
  SSH_SERVER_HOST: ${{ vars.SSH_SERVER_HOST }}
  SSH_SERVER_USER: ${{ vars.SSH_SERVER_USER }}
  SSH_SERVER_GHA_PRIVATE_KEY:  ${{ secrets.SSH_SERVER_GHA_PRIVATE_KEY }}

jobs:
  build:
    name: root-server deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@5b9dc5cf9560f2808ade896803b2f68cfcfdd52b
        with:
          environment-file: api/environment.yml
          init-shell: bash
      - name: Lint with Ruff
        run: python -m ruff check .
        working-directory: api
      - name: Run mypy
        run: python -m mypy .
        working-directory: api
      - name: Run pytest
        run: python -m pytest tests
        working-directory: api
      - name: force pull branch, and run Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_SERVER_HOST }}
          username: ${{ env.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_GHA_PRIVATE_KEY }}
          port: 22
          script: |
            cd /apps/tumai/space
            git fetch --all
            git reset --hard origin/main
            docker-compose build --no-cache
            docker-compose up -d --remove-orphans
