name: Build & deploy backend to tumai rootserver

on:
  release:
    types: [published]

env:
  ENVIRON=prod
  FIREBASE_ADMINSDK_CERTIFICATE=${{ secrets.FIREBASE_ADMINSDK_CERTIFICATE }}
  # [database environment]
  DB_HOST=space.db.staging
  DB_PORT=5432
  DB_NAME=space-db
  DB_USER=space-db
  DB_PASSWORD=${{ secrets.SPACE_DB_PASSWORD }}
  # [mail environment]
  MAIL_USERNAME=space@tum-ai.com
  MAIL_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}
  MAIL_FROM=space@tum-ai.com
  MAIL_PORT=587
  MAIL_SERVER=smtp.gmail.com
  MAIL_FROM_NAME=TUM.ai Space Team

jobs:
  build:
    name: root-server deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@5b9dc5cf9560f2808ade896803b2f68cfcfdd52b
        with:
          environment-file: api/environment.yml
          init-shell: bash
      - name: Lint with Ruff
        run: python -m ruff check .
        working-directory: api
      - name: Run mypy
        run: python -m mypy .
        working-directory: api
      - name: write secret file
        run: |
          mkdir -p api/.secrets             
          touch api/.secrets/tumai-space-firebase-adminsdk.json 
          echo "${{ secrets.FIREBASE_ADMINSDK_CERTIFICATE }}" > api/.secrets/tumai-space-firebase-adminsdk.json
      - name: Run pytest
        run: python -m pytest tests
        working-directory: api
      - name: Setup SSH to deployment root-server
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_SERVER_GHA_PRIVATE_KEY }}
      - name: force pull branch, and run Docker Compose
        run: ssh gha@91.210.224.56 'cd /apps/tumai/space && git fetch --all && git reset --hard origin/main && docker-compose build --no-cache && docker-compose up -d --remove-orphans'
  