name: API CI - lint and pytest

on:
  push:
    branches-ignore:
      - main
      - staging
    paths:
    - 'api/**'
  workflow_dispatch:

jobs:
  
  lint_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r api/requirements.txt

      - name: Check Python Formatting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./api"

      - name: Run pytest
        working-directory: ./app
        run: pytest
