name: Run pytest

on:
  push:
    branches-ignore:
      - main
      - staging
    paths:
    - 'api/**'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: ./app
        run: pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./app
        run: pytest
